name: MyWidgets
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #数据管理
  scoped_model: ^1.0.1
  provider: ^4.3.2+1
  #保存图片
  image_gallery_saver: ^1.5.0
  #浏览图片
  extended_image: ^0.9.0
  #选取图片
  image_picker: ^0.6.7+4
  #网络图片
  cached_network_image: ^2.2.0+1
  #下拉刷新
  pull_to_refresh: ^1.6.0
  #分享
  share_extend: ^1.1.9
  #网络请求
  dio: ^3.0.9
  #图标
  flutter_vector_icons: ^0.2.1
  #本地存储
  shared_preferences: ^0.5.10
  #toast
  fluttertoast: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
